# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/jh/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5540.8/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/jh/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5540.8/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jh/scidbsource

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jh/scidbsource

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/jh/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5540.8/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/jh/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5540.8/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/jh/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5540.8/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/jh/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5540.8/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"libdmalloc\" \"scidb\" \"scidb-client\" \"scidb-dev\" \"scidb-dev-tools\" \"scidb-jdbc\" \"scidb-plugins\" \"scidb-tests\" \"scidb-utils\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/jh/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5540.8/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/jh/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5540.8/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/jh/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5540.8/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/jh/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5540.8/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/home/jh/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5540.8/bin/cmake/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jh/scidbsource/CMakeFiles /home/jh/scidbsource/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jh/scidbsource/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named misc_files

# Build rule for target.
misc_files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 misc_files
.PHONY : misc_files

# fast build rule for target.
misc_files/fast:
	$(MAKE) -f CMakeFiles/misc_files.dir/build.make CMakeFiles/misc_files.dir/build
.PHONY : misc_files/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named src_package

# Build rule for target.
src_package: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 src_package
.PHONY : src_package

# fast build rule for target.
src_package/fast:
	$(MAKE) -f CMakeFiles/src_package.dir/build.make CMakeFiles/src_package.dir/build
.PHONY : src_package/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named json_lib

# Build rule for target.
json_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 json_lib
.PHONY : json_lib

# fast build rule for target.
json_lib/fast:
	$(MAKE) -f extern/lib_json/CMakeFiles/json_lib.dir/build.make extern/lib_json/CMakeFiles/json_lib.dir/build
.PHONY : json_lib/fast

#=============================================================================
# Target rules for targets named MurmurHash_lib

# Build rule for target.
MurmurHash_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MurmurHash_lib
.PHONY : MurmurHash_lib

# fast build rule for target.
MurmurHash_lib/fast:
	$(MAKE) -f extern/MurmurHash/CMakeFiles/MurmurHash_lib.dir/build.make extern/MurmurHash/CMakeFiles/MurmurHash_lib.dir/build
.PHONY : MurmurHash_lib/fast

#=============================================================================
# Target rules for targets named scidb

# Build rule for target.
scidb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scidb
.PHONY : scidb

# fast build rule for target.
scidb/fast:
	$(MAKE) -f src/CMakeFiles/scidb.dir/build.make src/CMakeFiles/scidb.dir/build
.PHONY : scidb/fast

#=============================================================================
# Target rules for targets named scidbclient

# Build rule for target.
scidbclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scidbclient
.PHONY : scidbclient

# fast build rule for target.
scidbclient/fast:
	$(MAKE) -f src/capi/CMakeFiles/scidbclient.dir/build.make src/capi/CMakeFiles/scidbclient.dir/build
.PHONY : scidbclient/fast

#=============================================================================
# Target rules for targets named network_lib

# Build rule for target.
network_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 network_lib
.PHONY : network_lib

# fast build rule for target.
network_lib/fast:
	$(MAKE) -f src/network/CMakeFiles/network_lib.dir/build.make src/network/CMakeFiles/network_lib.dir/build
.PHONY : network_lib/fast

#=============================================================================
# Target rules for targets named scidb_msg_lib

# Build rule for target.
scidb_msg_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scidb_msg_lib
.PHONY : scidb_msg_lib

# fast build rule for target.
scidb_msg_lib/fast:
	$(MAKE) -f src/network/proto/CMakeFiles/scidb_msg_lib.dir/build.make src/network/proto/CMakeFiles/scidb_msg_lib.dir/build
.PHONY : scidb_msg_lib/fast

#=============================================================================
# Target rules for targets named system_lib

# Build rule for target.
system_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 system_lib
.PHONY : system_lib

# fast build rule for target.
system_lib/fast:
	$(MAKE) -f src/system/CMakeFiles/system_lib.dir/build.make src/system/CMakeFiles/system_lib.dir/build
.PHONY : system_lib/fast

#=============================================================================
# Target rules for targets named catalog_lib

# Build rule for target.
catalog_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 catalog_lib
.PHONY : catalog_lib

# fast build rule for target.
catalog_lib/fast:
	$(MAKE) -f src/system/catalog/CMakeFiles/catalog_lib.dir/build.make src/system/catalog/CMakeFiles/catalog_lib.dir/build
.PHONY : catalog_lib/fast

#=============================================================================
# Target rules for targets named genmeta

# Build rule for target.
genmeta: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 genmeta
.PHONY : genmeta

# fast build rule for target.
genmeta/fast:
	$(MAKE) -f src/system/catalog/data/CMakeFiles/genmeta.dir/build.make src/system/catalog/data/CMakeFiles/genmeta.dir/build
.PHONY : genmeta/fast

#=============================================================================
# Target rules for targets named io_lib

# Build rule for target.
io_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 io_lib
.PHONY : io_lib

# fast build rule for target.
io_lib/fast:
	$(MAKE) -f src/smgr/io/CMakeFiles/io_lib.dir/build.make src/smgr/io/CMakeFiles/io_lib.dir/build
.PHONY : io_lib/fast

#=============================================================================
# Target rules for targets named rbac_lib

# Build rule for target.
rbac_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rbac_lib
.PHONY : rbac_lib

# fast build rule for target.
rbac_lib/fast:
	$(MAKE) -f src/rbac/CMakeFiles/rbac_lib.dir/build.make src/rbac/CMakeFiles/rbac_lib.dir/build
.PHONY : rbac_lib/fast

#=============================================================================
# Target rules for targets named util_lib

# Build rule for target.
util_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util_lib
.PHONY : util_lib

# fast build rule for target.
util_lib/fast:
	$(MAKE) -f src/util/CMakeFiles/util_lib.dir/build.make src/util/CMakeFiles/util_lib.dir/build
.PHONY : util_lib/fast

#=============================================================================
# Target rules for targets named dmalloc

# Build rule for target.
dmalloc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dmalloc
.PHONY : dmalloc

# fast build rule for target.
dmalloc/fast:
	$(MAKE) -f src/util/dmalloc/CMakeFiles/dmalloc.dir/build.make src/util/dmalloc/CMakeFiles/dmalloc.dir/build
.PHONY : dmalloc/fast

#=============================================================================
# Target rules for targets named compression_lib

# Build rule for target.
compression_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compression_lib
.PHONY : compression_lib

# fast build rule for target.
compression_lib/fast:
	$(MAKE) -f src/util/compression/CMakeFiles/compression_lib.dir/build.make src/util/compression/CMakeFiles/compression_lib.dir/build
.PHONY : compression_lib/fast

#=============================================================================
# Target rules for targets named monitor_lib

# Build rule for target.
monitor_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monitor_lib
.PHONY : monitor_lib

# fast build rule for target.
monitor_lib/fast:
	$(MAKE) -f src/monitor/CMakeFiles/monitor_lib.dir/build.make src/monitor/CMakeFiles/monitor_lib.dir/build
.PHONY : monitor_lib/fast

#=============================================================================
# Target rules for targets named mpi_common

# Build rule for target.
mpi_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpi_common
.PHONY : mpi_common

# fast build rule for target.
mpi_common/fast:
	$(MAKE) -f src/mpi/CMakeFiles/mpi_common.dir/build.make src/mpi/CMakeFiles/mpi_common.dir/build
.PHONY : mpi_common/fast

#=============================================================================
# Target rules for targets named mpi

# Build rule for target.
mpi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpi
.PHONY : mpi

# fast build rule for target.
mpi/fast:
	$(MAKE) -f src/mpi/CMakeFiles/mpi.dir/build.make src/mpi/CMakeFiles/mpi.dir/build
.PHONY : mpi/fast

#=============================================================================
# Target rules for targets named mpi_slave_common

# Build rule for target.
mpi_slave_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpi_slave_common
.PHONY : mpi_slave_common

# fast build rule for target.
mpi_slave_common/fast:
	$(MAKE) -f src/mpi/slaving/CMakeFiles/mpi_slave_common.dir/build.make src/mpi/slaving/CMakeFiles/mpi_slave_common.dir/build
.PHONY : mpi_slave_common/fast

#=============================================================================
# Target rules for targets named mpi_slave_direct

# Build rule for target.
mpi_slave_direct: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpi_slave_direct
.PHONY : mpi_slave_direct

# fast build rule for target.
mpi_slave_direct/fast:
	$(MAKE) -f src/mpi/slaving/CMakeFiles/mpi_slave_direct.dir/build.make src/mpi/slaving/CMakeFiles/mpi_slave_direct.dir/build
.PHONY : mpi_slave_direct/fast

#=============================================================================
# Target rules for targets named mpi_slave_scidb

# Build rule for target.
mpi_slave_scidb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpi_slave_scidb
.PHONY : mpi_slave_scidb

# fast build rule for target.
mpi_slave_scidb/fast:
	$(MAKE) -f src/mpi/slaving/CMakeFiles/mpi_slave_scidb.dir/build.make src/mpi/slaving/CMakeFiles/mpi_slave_scidb.dir/build
.PHONY : mpi_slave_scidb/fast

#=============================================================================
# Target rules for targets named dense_linear_algebra

# Build rule for target.
dense_linear_algebra: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dense_linear_algebra
.PHONY : dense_linear_algebra

# fast build rule for target.
dense_linear_algebra/fast:
	$(MAKE) -f src/dense_linear_algebra/CMakeFiles/dense_linear_algebra.dir/build.make src/dense_linear_algebra/CMakeFiles/dense_linear_algebra.dir/build
.PHONY : dense_linear_algebra/fast

#=============================================================================
# Target rules for targets named linear_algebra

# Build rule for target.
linear_algebra: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linear_algebra
.PHONY : linear_algebra

# fast build rule for target.
linear_algebra/fast:
	$(MAKE) -f src/linear_algebra/CMakeFiles/linear_algebra.dir/build.make src/linear_algebra/CMakeFiles/linear_algebra.dir/build
.PHONY : linear_algebra/fast

#=============================================================================
# Target rules for targets named jdbc_build

# Build rule for target.
jdbc_build: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jdbc_build
.PHONY : jdbc_build

# fast build rule for target.
jdbc_build/fast:
	$(MAKE) -f src/jdbc/CMakeFiles/jdbc_build.dir/build.make src/jdbc/CMakeFiles/jdbc_build.dir/build
.PHONY : jdbc_build/fast

#=============================================================================
# Target rules for targets named storage_lib

# Build rule for target.
storage_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 storage_lib
.PHONY : storage_lib

# fast build rule for target.
storage_lib/fast:
	$(MAKE) -f src/storage/CMakeFiles/storage_lib.dir/build.make src/storage/CMakeFiles/storage_lib.dir/build
.PHONY : storage_lib/fast

#=============================================================================
# Target rules for targets named array_lib

# Build rule for target.
array_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 array_lib
.PHONY : array_lib

# fast build rule for target.
array_lib/fast:
	$(MAKE) -f src/array/CMakeFiles/array_lib.dir/build.make src/array/CMakeFiles/array_lib.dir/build
.PHONY : array_lib/fast

#=============================================================================
# Target rules for targets named scalar_proc_lib

# Build rule for target.
scalar_proc_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scalar_proc_lib
.PHONY : scalar_proc_lib

# fast build rule for target.
scalar_proc_lib/fast:
	$(MAKE) -f src/query/CMakeFiles/scalar_proc_lib.dir/build.make src/query/CMakeFiles/scalar_proc_lib.dir/build
.PHONY : scalar_proc_lib/fast

#=============================================================================
# Target rules for targets named qproc_lib

# Build rule for target.
qproc_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qproc_lib
.PHONY : qproc_lib

# fast build rule for target.
qproc_lib/fast:
	$(MAKE) -f src/query/CMakeFiles/qproc_lib.dir/build.make src/query/CMakeFiles/qproc_lib.dir/build
.PHONY : qproc_lib/fast

#=============================================================================
# Target rules for targets named ops_lib

# Build rule for target.
ops_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ops_lib
.PHONY : ops_lib

# fast build rule for target.
ops_lib/fast:
	$(MAKE) -f src/query/ops/CMakeFiles/ops_lib.dir/build.make src/query/ops/CMakeFiles/ops_lib.dir/build
.PHONY : ops_lib/fast

#=============================================================================
# Target rules for targets named upgrade_chunk_index

# Build rule for target.
upgrade_chunk_index: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upgrade_chunk_index
.PHONY : upgrade_chunk_index

# fast build rule for target.
upgrade_chunk_index/fast:
	$(MAKE) -f src/query/ops/upgradeChunkIndex/CMakeFiles/upgrade_chunk_index.dir/build.make src/query/ops/upgradeChunkIndex/CMakeFiles/upgrade_chunk_index.dir/build
.PHONY : upgrade_chunk_index/fast

#=============================================================================
# Target rules for targets named benchGen

# Build rule for target.
benchGen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchGen
.PHONY : benchGen

# fast build rule for target.
benchGen/fast:
	$(MAKE) -f utils/CMakeFiles/benchGen.dir/build.make utils/CMakeFiles/benchGen.dir/build
.PHONY : benchGen/fast

#=============================================================================
# Target rules for targets named iquery

# Build rule for target.
iquery: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iquery
.PHONY : iquery

# fast build rule for target.
iquery/fast:
	$(MAKE) -f utils/iquery/CMakeFiles/iquery.dir/build.make utils/iquery/CMakeFiles/iquery.dir/build
.PHONY : iquery/fast

#=============================================================================
# Target rules for targets named indexmapper

# Build rule for target.
indexmapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 indexmapper
.PHONY : indexmapper

# fast build rule for target.
indexmapper/fast:
	$(MAKE) -f utils/indexmapper/CMakeFiles/indexmapper.dir/build.make utils/indexmapper/CMakeFiles/indexmapper.dir/build
.PHONY : indexmapper/fast

#=============================================================================
# Target rules for targets named gen_matrix

# Build rule for target.
gen_matrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen_matrix
.PHONY : gen_matrix

# fast build rule for target.
gen_matrix/fast:
	$(MAKE) -f tests/data_gen/CMakeFiles/gen_matrix.dir/build.make tests/data_gen/CMakeFiles/gen_matrix.dir/build
.PHONY : gen_matrix/fast

#=============================================================================
# Target rules for targets named dgenerator

# Build rule for target.
dgenerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dgenerator
.PHONY : dgenerator

# fast build rule for target.
dgenerator/fast:
	$(MAKE) -f tests/data_gen/CMakeFiles/dgenerator.dir/build.make tests/data_gen/CMakeFiles/dgenerator.dir/build
.PHONY : dgenerator/fast

#=============================================================================
# Target rules for targets named arg_separator

# Build rule for target.
arg_separator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arg_separator
.PHONY : arg_separator

# fast build rule for target.
arg_separator/fast:
	$(MAKE) -f tests/harness/CMakeFiles/arg_separator.dir/build.make tests/harness/CMakeFiles/arg_separator.dir/build
.PHONY : arg_separator/fast

#=============================================================================
# Target rules for targets named scidbtestharness

# Build rule for target.
scidbtestharness: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scidbtestharness
.PHONY : scidbtestharness

# fast build rule for target.
scidbtestharness/fast:
	$(MAKE) -f tests/harness/CMakeFiles/scidbtestharness.dir/build.make tests/harness/CMakeFiles/scidbtestharness.dir/build
.PHONY : scidbtestharness/fast

#=============================================================================
# Target rules for targets named scidbtest

# Build rule for target.
scidbtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scidbtest
.PHONY : scidbtest

# fast build rule for target.
scidbtest/fast:
	$(MAKE) -f tests/harness/CMakeFiles/scidbtest.dir/build.make tests/harness/CMakeFiles/scidbtest.dir/build
.PHONY : scidbtest/fast

#=============================================================================
# Target rules for targets named preparecdashreport

# Build rule for target.
preparecdashreport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 preparecdashreport
.PHONY : preparecdashreport

# fast build rule for target.
preparecdashreport/fast:
	$(MAKE) -f tests/harness/CMakeFiles/preparecdashreport.dir/build.make tests/harness/CMakeFiles/preparecdashreport.dir/build
.PHONY : preparecdashreport/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) -f tests/unit/CMakeFiles/unit_tests.dir/build.make tests/unit/CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

#=============================================================================
# Target rules for targets named point

# Build rule for target.
point: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 point
.PHONY : point

# fast build rule for target.
point/fast:
	$(MAKE) -f examples/point/CMakeFiles/point.dir/build.make examples/point/CMakeFiles/point.dir/build
.PHONY : point/fast

#=============================================================================
# Target rules for targets named rational

# Build rule for target.
rational: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rational
.PHONY : rational

# fast build rule for target.
rational/fast:
	$(MAKE) -f examples/rational/CMakeFiles/rational.dir/build.make examples/rational/CMakeFiles/rational.dir/build
.PHONY : rational/fast

#=============================================================================
# Target rules for targets named complex

# Build rule for target.
complex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 complex
.PHONY : complex

# fast build rule for target.
complex/fast:
	$(MAKE) -f examples/complex/CMakeFiles/complex.dir/build.make examples/complex/CMakeFiles/complex.dir/build
.PHONY : complex/fast

#=============================================================================
# Target rules for targets named ra_decl

# Build rule for target.
ra_decl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ra_decl
.PHONY : ra_decl

# fast build rule for target.
ra_decl/fast:
	$(MAKE) -f examples/ra_decl/CMakeFiles/ra_decl.dir/build.make examples/ra_decl/CMakeFiles/ra_decl.dir/build
.PHONY : ra_decl/fast

#=============================================================================
# Target rules for targets named more_math

# Build rule for target.
more_math: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 more_math
.PHONY : more_math

# fast build rule for target.
more_math/fast:
	$(MAKE) -f examples/more_math/CMakeFiles/more_math.dir/build.make examples/more_math/CMakeFiles/more_math.dir/build
.PHONY : more_math/fast

#=============================================================================
# Target rules for targets named misc

# Build rule for target.
misc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 misc
.PHONY : misc

# fast build rule for target.
misc/fast:
	$(MAKE) -f examples/misc/CMakeFiles/misc.dir/build.make examples/misc/CMakeFiles/misc.dir/build
.PHONY : misc/fast

#=============================================================================
# Target rules for targets named match

# Build rule for target.
match: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 match
.PHONY : match

# fast build rule for target.
match/fast:
	$(MAKE) -f examples/match/CMakeFiles/match.dir/build.make examples/match/CMakeFiles/match.dir/build
.PHONY : match/fast

#=============================================================================
# Target rules for targets named bestmatch

# Build rule for target.
bestmatch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bestmatch
.PHONY : bestmatch

# fast build rule for target.
bestmatch/fast:
	$(MAKE) -f examples/bestmatch/CMakeFiles/bestmatch.dir/build.make examples/bestmatch/CMakeFiles/bestmatch.dir/build
.PHONY : bestmatch/fast

#=============================================================================
# Target rules for targets named savebmp

# Build rule for target.
savebmp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 savebmp
.PHONY : savebmp

# fast build rule for target.
savebmp/fast:
	$(MAKE) -f examples/savebmp/CMakeFiles/savebmp.dir/build.make examples/savebmp/CMakeFiles/savebmp.dir/build
.PHONY : savebmp/fast

#=============================================================================
# Target rules for targets named operators

# Build rule for target.
operators: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 operators
.PHONY : operators

# fast build rule for target.
operators/fast:
	$(MAKE) -f examples/operators/CMakeFiles/operators.dir/build.make examples/operators/CMakeFiles/operators.dir/build
.PHONY : operators/fast

#=============================================================================
# Target rules for targets named fits

# Build rule for target.
fits: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fits
.PHONY : fits

# fast build rule for target.
fits/fast:
	$(MAKE) -f examples/fits/CMakeFiles/fits.dir/build.make examples/fits/CMakeFiles/fits.dir/build
.PHONY : fits/fast

#=============================================================================
# Target rules for targets named example_udos

# Build rule for target.
example_udos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_udos
.PHONY : example_udos

# fast build rule for target.
example_udos/fast:
	$(MAKE) -f examples/example_udos/CMakeFiles/example_udos.dir/build.make examples/example_udos/CMakeFiles/example_udos.dir/build
.PHONY : example_udos/fast

#=============================================================================
# Target rules for targets named tile_integration

# Build rule for target.
tile_integration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tile_integration
.PHONY : tile_integration

# fast build rule for target.
tile_integration/fast:
	$(MAKE) -f examples/tile_integration/CMakeFiles/tile_integration.dir/build.make examples/tile_integration/CMakeFiles/tile_integration.dir/build
.PHONY : tile_integration/fast

examples/point/point.o: examples/point/point.cpp.o

.PHONY : examples/point/point.o

# target to build an object file
examples/point/point.cpp.o:
	$(MAKE) -f CMakeFiles/misc_files.dir/build.make CMakeFiles/misc_files.dir/examples/point/point.cpp.o
.PHONY : examples/point/point.cpp.o

examples/point/point.i: examples/point/point.cpp.i

.PHONY : examples/point/point.i

# target to preprocess a source file
examples/point/point.cpp.i:
	$(MAKE) -f CMakeFiles/misc_files.dir/build.make CMakeFiles/misc_files.dir/examples/point/point.cpp.i
.PHONY : examples/point/point.cpp.i

examples/point/point.s: examples/point/point.cpp.s

.PHONY : examples/point/point.s

# target to generate assembly for a file
examples/point/point.cpp.s:
	$(MAKE) -f CMakeFiles/misc_files.dir/build.make CMakeFiles/misc_files.dir/examples/point/point.cpp.s
.PHONY : examples/point/point.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... misc_files"
	@echo "... uninstall"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousMemCheck"
	@echo "... Nightly"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... install/local"
	@echo "... Continuous"
	@echo "... NightlyBuild"
	@echo "... NightlyStart"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ContinuousConfigure"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalUpdate"
	@echo "... test"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalBuild"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalMemCheck"
	@echo "... Experimental"
	@echo "... NightlySubmit"
	@echo "... ExperimentalSubmit"
	@echo "... ContinuousStart"
	@echo "... src_package"
	@echo "... ContinuousUpdate"
	@echo "... json_lib"
	@echo "... MurmurHash_lib"
	@echo "... scidb"
	@echo "... scidbclient"
	@echo "... network_lib"
	@echo "... scidb_msg_lib"
	@echo "... system_lib"
	@echo "... catalog_lib"
	@echo "... genmeta"
	@echo "... io_lib"
	@echo "... rbac_lib"
	@echo "... util_lib"
	@echo "... dmalloc"
	@echo "... compression_lib"
	@echo "... monitor_lib"
	@echo "... mpi_common"
	@echo "... mpi"
	@echo "... mpi_slave_common"
	@echo "... mpi_slave_direct"
	@echo "... mpi_slave_scidb"
	@echo "... dense_linear_algebra"
	@echo "... linear_algebra"
	@echo "... jdbc_build"
	@echo "... storage_lib"
	@echo "... array_lib"
	@echo "... scalar_proc_lib"
	@echo "... qproc_lib"
	@echo "... ops_lib"
	@echo "... upgrade_chunk_index"
	@echo "... benchGen"
	@echo "... iquery"
	@echo "... indexmapper"
	@echo "... gen_matrix"
	@echo "... dgenerator"
	@echo "... arg_separator"
	@echo "... scidbtestharness"
	@echo "... scidbtest"
	@echo "... preparecdashreport"
	@echo "... unit_tests"
	@echo "... point"
	@echo "... rational"
	@echo "... complex"
	@echo "... ra_decl"
	@echo "... more_math"
	@echo "... misc"
	@echo "... match"
	@echo "... bestmatch"
	@echo "... savebmp"
	@echo "... operators"
	@echo "... fits"
	@echo "... example_udos"
	@echo "... tile_integration"
	@echo "... examples/point/point.o"
	@echo "... examples/point/point.i"
	@echo "... examples/point/point.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

